### ISSUE TITLE
[all plugins] Comments

### ISSUE THREAD

**Issue by GoogleCodeExporter** [roundcubevnz/myroundcube#252]
```
I appreciate your comments here ...

```

Original issue reported on code.google.com by `rol...@liebl.ath.cx` on 26 Oct 2011 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi,
in the README file in your Accounts-plugin you wrote "copy <install 
directory>\plugins\accounts\config\config.inc.php.dist as <install 
directory>\plugins\accounts\config\config.inc.php" but the dist-file is in the 
accounts-folder itself and there is no config folder. Could you please change 
this text in the readme.
Great work. I like your projekt. Just keep it going on :)
Kind regards, Michael.
```

Original comment by `google...@mischolz.de` on 3 Nov 2011 at 1:04

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Thanks! I missed to update the README.
```

Original comment by `rol...@liebl.ath.cx` on 3 Nov 2011 at 7:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `rol...@liebl.ath.cx` on 17 Feb 2012 at 7:52
- Changed title: **[All Plugins] Comments**

**Comment by GoogleCodeExporter** [comment]
Original comment by `rol...@liebl.ath.cx` on 17 Feb 2012 at 7:54
- Changed title: **[all plugins] Comments**

**Comment by GoogleCodeExporter** [comment]
```
Hi Roland,

Your work on the Roundcube Plugins is very much appreciated by me. I use it 
quiet often.
I have a short question though. Is it possible to use Z-push with the calendar 
plugin you created? That would be great!

Regards,
Arnaud
```

Original comment by `naud...@gmail.com` on 5 Mar 2012 at 10:46

**Comment by GoogleCodeExporter** [comment]
```
z-push (an implemenation of activsync protocol) is not support and there are no 
plans to implement it.
```

Original comment by `rol...@liebl.ath.cx` on 5 Mar 2012 at 2:48

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hello, I tried to register the plugin "self register" the new cpanel, but no 
longer works. I managed to find instructions for registering xmlapi cPanel. See 
http://forums.glowhost.com/programming-talk/using-cpanel-api-creating-email-acco
unt-forwarders-your-own-php-scripts-2798.html

It works with XMLAPI very well, but I can not integrate it into your plugin 
registration. Please message me if he could help someone with it. Thank you. 
Kozoroh info@rexvox.com
```

Original comment by `a.pool.d...@gmail.com` on 21 Mar 2012 at 10:52

Attachments:
- [register-xmlapi.zip](https://storage.googleapis.com/google-code-attachments/myroundcube/issue-252/comment-10/register-xmlapi.zip)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for Your all plugins. Kozoroh
```

Original comment by `a.pool.d...@gmail.com` on 21 Mar 2012 at 10:54

**Comment by GoogleCodeExporter** [comment]
```
@ comment 10:

I would need a cPanel test environment to implement this.
```

Original comment by `rol...@liebl.ath.cx` on 22 Mar 2012 at 5:19

**Comment by GoogleCodeExporter** [comment]
```
Hi,
did you support the beta 0.8 Version of Roundcube?
Kind Regards
Ben
```

Original comment by `Leitschu...@googlemail.com` on 29 Mar 2012 at 1:00

**Comment by GoogleCodeExporter** [comment]
```
No, not yet. I wait for Roundcube 0.8 Release Candidate. Nevertheless, most 
plugins will run on 0.8. Maybe they need skin adjustments.
```

Original comment by `rol...@liebl.ath.cx` on 29 Mar 2012 at 1:49

**Comment by GoogleCodeExporter** [comment]
```
Comment 10 + comment 12:

I would need a cPanel test environment to implement this.
-----------
Hi, thank you for your reply. Cpanel - resseler acount I can give you. I have 
one opened for testing. Please report to info/@/rexvox.com. I wrote you an 
email myself, but I do not know your full address.
thank you
Kozoroh
```

Original comment by `a.pool.d...@gmail.com` on 31 Mar 2012 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
Mailto myroundcube at mail4us dot net.
```

Original comment by `rol...@liebl.ath.cx` on 1 Apr 2012 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
Added cpanel-xmlapi driver.
```

Original comment by `rol...@liebl.ath.cx` on 12 Apr 2012 at 5:53

**Comment by GoogleCodeExporter** [comment]
```
"accounts" plugin <select> list not right if a local account represent.

Finally, I found a way to repair this, modify \plugins\accounts\accounts.php:
//$user = $rcmail->output->current_username(null); -- comment out this
$user = $rcmail->user->data['username'];  --  andd this

I'm not sure what I'm doing is right.
```

Original comment by `fun...@gmail.com` on 16 Jul 2012 at 1:55

**Comment by GoogleCodeExporter** [comment]
```
@ comment 18:

Use plugin_manager to fetch recent code. This bug has been fixed already.
```

Original comment by `rol...@liebl.ath.cx` on 16 Jul 2012 at 2:04

**Comment by GoogleCodeExporter** [comment]
```
Tanks.
I'm using roundcube 0.7.2, does the lastest version myroundcube check out from 
svn compatible with roundcube 0.7.2?
```

Original comment by `fun...@gmail.com` on 16 Jul 2012 at 3:13

**Comment by GoogleCodeExporter** [comment]
```
This repository is only for my internal code documentation and issue tracking. 
To fetch recent code, you have to install plugin_manager. Note: Code in this 
repository may not work. It is developement code. Don't check out code from 
here. Please visit http://myroundcube.com.
```

Original comment by `myroundc...@gmail.com` on 16 Jul 2012 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
When I click "Download Zip-Archive", nothing displayed.
Can't connect 
http://mirror.mail4us.net/?_action=plugin.plugin_server_request&_hl=zh_CN    , 
or http://mirror.mail4us.net/?_action=plugin.plugin_server_request&_hl=en_US, 
to download the right plugin.
```

Original comment by `fun...@gmail.com` on 17 Jul 2012 at 1:30

**Comment by GoogleCodeExporter** [comment]
```
It works. I have just checked it from one of my test hosts.
```

Original comment by `myroundc...@gmail.com` on 17 Jul 2012 at 3:27

**Comment by GoogleCodeExporter** [comment]
```
It's weird, I still can't download. Even using another web browser, in home or 
office.
Is there any other way to download?
```

Original comment by `fun...@gmail.com` on 18 Jul 2012 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
Ok, after update to 0.8-rc, I can download now.
Thanks.
```

Original comment by `fun...@gmail.com` on 18 Jul 2012 at 2:15

**Comment by GoogleCodeExporter** [comment]
```
Calendar plugin, popup notice doesn't work, but email notice is ok.
Can you givem me some tips to debug this?
```

Original comment by `fun...@gmail.com` on 19 Jul 2012 at 8:25

**Comment by GoogleCodeExporter** [comment]
```
I'm sorry. English is not my native language and it looks like it isn't yours. 
Please try to be more detailed. I simply don't understand your comment.
```

Original comment by `myroundc...@gmail.com` on 19 Jul 2012 at 11:11

**Comment by GoogleCodeExporter** [comment]
```
Popup reminder doesn't work in calendar plugin, but e-mail reminder is ok.
There is no error in log. How to find out what's wrong with it?
```

Original comment by `fun...@gmail.com` on 19 Jul 2012 at 10:31

**Comment by GoogleCodeExporter** [comment]
```
Install Firebug and check if there are Javascript errors.
```

Original comment by `myroundc...@gmail.com` on 20 Jul 2012 at 3:56

**Comment by GoogleCodeExporter** [comment]
```
SyntaxError: invalid increment operand
  this.orientation);this._refreshValue()...s="ui-icon ui-icon-circle-triangle-'+     jquery...2555372 (line 7)
TypeError: e.datepicker is undefined
  this._defaults.hourMin)%this._defaults....timepicker.version="0.9.7"})(jQuery);    jquery...2555372 (line 7)
TypeError: $("#jqdatepicker").datepicker is not a function
  function calendar_gui(){window.rcmail&...ng("_view"):a.settings.default_view}}     calend...2555370 (line 1)
```

Original comment by `fun...@gmail.com` on 22 Jul 2012 at 6:52

**Comment by GoogleCodeExporter** [comment]
```
There's nothing displayed in "calendar" page 
(/?_task=dummy&_action=plugin.calendar) using firefox, but it's ok using IE and 
Opera.
```

Original comment by `fun...@gmail.com` on 22 Jul 2012 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
After reinstall roundcube, e-mail reminder does't work too.
How to make it work.
Help me.
Thanks.

Fatal error: Call to undefined function microtime_float() in 
C:\wamp\www\mail\plugins\calendar\cron\reminders.php on line 4
```

Original comment by `fun...@gmail.com` on 22 Jul 2012 at 6:10

**Comment by GoogleCodeExporter** [comment]
```
microtime_float is defined in line 39 of reminders.php. So, I don't understand 
the issue.

Please notice: This Repository is not a support forum. Either goto 
http://roundcubeforum.net or to http://myroundcube-plugins.40634.n3.nabble.com/

I will ignore support requests in this thread in future.
```

Original comment by `myroundc...@gmail.com` on 22 Jul 2012 at 6:40

**Comment by GoogleCodeExporter** [comment]
```
Hi,

what about roundcube 0.8.0 ? whereis the vkeyboard and others ?
thanks.
```

Original comment by `selcuk.y...@gmail.com` on 15 Aug 2012 at 2:19

Attachments:
- [Untitled.png](https://storage.googleapis.com/google-code-attachments/myroundcube/issue-252/comment-34/Untitled.png)

**Comment by GoogleCodeExporter** [comment]
```
at the risk of sounding like a total newb, can I ask how to install a roundcube 
plugin on a windows machine? Yes, I know I know, I shouldn't be using windows, 
but its a work computer and I'm trying to find a way to give me more 
flexibility in terms of organizing my email and Outlook is horrible. I like the 
customizability of roundcube so far :)
```

Original comment by `gabe.el...@gmail.com` on 7 Oct 2012 at 7:47

**Comment by GoogleCodeExporter** [comment]
```
Hi, Roundcube is not desktop application, but it run on server on internet.
```

Original comment by `a.pool.d...@gmail.com` on 7 Oct 2012 at 7:58

**Comment by GoogleCodeExporter** [comment]
```
Im having problems with the calendar plugin using caldav on a radicale caldav 
server... Has anyone had any luck with this setup? Or can anyone suggest 
anything
```

Original comment by `adam.cop...@gmail.com` on 16 Nov 2012 at 4:42

**Comment by GoogleCodeExporter** [comment]
```
README for Calendar points to http://myroundcube.com/myroundcube-plugins/, 
which has a one liner about the Calendar. Nothing about dependencies or the 
fact it will not work with RC 0.9.
```

Original comment by `crim...@gmail.com` on 16 Feb 2013 at 8:54

**Comment by GoogleCodeExporter** [comment]
```
@crimjob

The fact... the fact is that you posted on February 16th and Roundcube 
0.9.0-stable shipped on April 15th. Please keep in mind that we do not and 
cannot support alpha and beta versions. Shifting our development and plugins 
update is quite a lot of work. We officially released 0.9.0 compatible plugins 
one week after Roundcube Webmail 0.9.0-stable was made available.  Did you 
subscribe to our newsletter? => 
http://newsletter.myroundcube.com/news/show/100/0-GUEST

```

Original comment by `myroundc...@gmail.com` on 7 May 2013 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Please use http://forum.myroundcube.com for comments.
```

Original comment by `roland.l...@gmail.com` on 15 Aug 2013 at 7:09
